### ISSUE TITLE
do the same thing with mekanism portals

### ISSUE THREAD

**Issue by 1971chevycamaro** [Johni0702/BetterPortals#100]
mekanism has their own portals it would be cool if you added compatibility with it if it is installed

**Comment by Khazoda** [comment]
or even just linkable portals as a standalone feature, being able to link bases with a friend or put a portal in a different dimension and have it show that would be super cool

**Comment by pupnewfster** [comment]
@Johni0702 
Was reading the changelog because the concept of the mod interests me, and I noticed this change. Not sure if anything will break and maybe I will test it at some point, but figured I might as well give you a heads up that in 9.8.0, we are updating a lot of things to do with rendering. (It should all basically work the same way as it does now in terms of visually how it renders but changed from using GL11 all over the place to GlStateManager. And looking at the commit you made it does reference RenderTeleporter (though unsure how much of a difference things will make). If you are curious about what is changing you can ctrl+f the files changed for `RenderTeleporter` in this PR https://github.com/mekanism/Mekanism/pull/5494

Hopefully the compat you added in your mod won't break from this change, but if it does wanted to make it easier for you to know why so that you can track it down and fix it quicker.

**Comment by Johni0702** [comment]
@pupnewfster Thanks for the heads up!

Looking at the changes in the PR, I don't think anything will be breaking.
Really the only assumption about the implementation details in `RenderTeleporter` which I'm making is that overriding [bindTexture](https://github.com/Johni0702/BetterPortals/blob/d407920f114d25ffe9a269a33f67f66c5a0520ea/src/mekanism/kotlin/de/johni0702/minecraft/betterportals/impl/mekanism/client/tile/renderer/RenderBetterTeleporter.kt#L44-L49) works as a hook for changing the opacity of the rendered portal surface and that still seems to be valid (though I should probably stop using raw GL there as well then).
