### ISSUE TITLE
Game crashes when opening portal

### ISSUE THREAD

**Issue by LemonHeadOnGit** [Johni0702/BetterPortals#104]
Hi.

For some unknown reason, whenever I open a portal, the portal takes about 30 seconds before it does anything, it then shows a blank white-blue screen, then proceeds to crash.
Here is the crash report:
https://pastebin.com/KLrgHQGC

Thanks,
~L

**Comment by Johni0702** [comment]
Try removing third-party mods until you find the minimal configuration which triggers your issue.
Once done, post the updated crash report.
Please also post the full log, there may be errors in there which didn't immediately cause a crash but were indirectly responsible for one.

**Comment by LemonHeadOnGit** [comment]
Hi.

I found the problem.

I forgot to remove optifine from the mods list, which caused the crashing.

Sorry about that.
~L

**Comment by Ramanati** [comment]
Was having the same issues as well, and this fixed it. Had to remove Optifine.

**Comment by Johni0702** [comment]
Is this still happening with the latest BP version (0.2.3 as of writing)?
If so, please post an updated crash report.

**Comment by LemonHeadOnGit** [comment]
I updated and put Optifine back. Well, the game stopped crashing, but this happened. Not sure what caused it though. It works fine now with the latest update. I think the shader switch caused this problem, because if you use this mod with shaders, the portal flickers between black and normal (as if you weren't using the mod). Thanks for the help though.

![2019-08-16_18 07 43](https://user-images.githubusercontent.com/41242131/63182500-00d09900-c053-11e9-88d7-e6e0e912bec0.png)
![2019-08-16_18 07 52](https://user-images.githubusercontent.com/41242131/63182502-01692f80-c053-11e9-9a1a-c4b5ec833f1a.png)
![2019-08-16_18 08 40](https://user-images.githubusercontent.com/41242131/63182503-01692f80-c053-11e9-92a7-be0a9771da51.png)

**Comment by Johni0702** [comment]
Yeah, OF's shader implementation is incompatible with multiple worlds (and sp614x does not plan to fix that).
Additionally, toggling certain OF settings which affect rendering (those which would cause chunks to reload when being toggled) can cause issues when toggled while a portal is nearby (since it doesn't know about other worlds and therefore doesn't reload them). It should fix itself (assuming it didn't crash) when you re-load the portal (either by walking away from it or quitting and rejoining).
