### ISSUE TITLE
Hats do not render in-between dimensions

### ISSUE THREAD

**Issue by SnaveSutit** [Johni0702/BetterPortals#121]
I don't know if this is an issue with the [hats mod](https://www.curseforge.com/minecraft/mc-mods/hats) , or with BP. But you can't see hats on players who are in the nether from the Overworld. This is impossible to test in single player.

**Comment by Johni0702** [comment]
While looking into the other issue, I came across code in the Hats mod which would cause something similar as what you're describing (hats are actually entities and they are only spawned in the main world) but I hadn't bothered to test it (because of the MP requirement).
I've already included the issue in my report on the Hats issue tracker and have now also linked this ticket as confirmation for it.
Closing because it's up to the Hats mod to fix.

**Comment by SnaveSutit** [comment]
I thought you said something like that, but I wanted to be sure ;)
