### ISSUE TITLE
Incompatible with Twilight Forest 3.9 (as opposed to 3.8)

### ISSUE THREAD

**Issue by SpGilbert** [Johni0702/BetterPortals#143]
[crash-2019-07-18_17.05.18-client.txt](https://github.com/Johni0702/BetterPortals/files/3408499/crash-2019-07-18_17.05.18-client.txt)

**Comment by SpGilbert** [comment]
and from the atum 2 discord.
![Screenshot (4)](https://user-images.githubusercontent.com/42950385/61495611-72032a80-a987-11e9-86ff-af50fa208d76.png)

**Comment by Johni0702** [comment]
I first implemented support for TF a very long while ago and it looks like something in a newer version has changed (you can try using some older version until it's fixed, I've been using 3.6.345 in dev).
I should be easily able to fix this in the next version but that might have to wait till tomorrow.

**Comment by Johni0702** [comment]
Turns out there were other changes as well. At least one of which I cannot support in a backwards compatible way which means I can only support TF 3.8 or TF 3.9 but not both at the same time.
Since TF 3.9 is still in the alpha stage, I'll wait for its release to fix this issue.
For now, please downgrade to TF 3.8 or disable its integration the the BP config.
