### ISSUE TITLE
Issue with The Midnight mod

### ISSUE THREAD

**Issue by ProfessorMeowingtons** [Johni0702/BetterPortals#149]
Just started with mods yesterday, so I have a bunch more mods installed and I don't know if this is the correct way to go about things, but here goes. Every time I enter the Midnight dimension it does this weird phasing-bubbly effect, and it's all fine until I die in there and respawn. A couple seconds after Minecraft crashes. I did the same without Better Portals installed and it was all fine.
[crash-2019-07-19_23.18.41-client.txt](https://github.com/Johni0702/BetterPortals/files/3413199/crash-2019-07-19_23.18.41-client.txt)
https://www.curseforge.com/minecraft/mc-mods/the-midnight

**Comment by Johni0702** [comment]
I tried installing BP, the midnight mod, autoreglib (because it's part of the stacktrace) and quark (because it uses autoreglib) but I'm unable to reproduce this.

General rules of thumb when reporting bugs to mods:
- Logs (you provided the crash report which is good enough)
- Always use the latest version of mods. Note that the latest version (BP 0.2.3) might not always be the default download (BP 0.1.6) on CurseForge.
- Try to remove as many unrelated mods as possible. BUT even though this issue may be unrelated to the midnight mod (in case it's the same as #140, certainly looks very similar), if the midnight mod allows you to reliably reproduce it, then by all means keep it. Being able to reliably (and within reasonable time) reproduce an issue is the most important thing.
- Even though this is a bit lengthy to read and not MC specific, it contains much generally applicable advice for how to report bugs effectively and at least 80% of all bug reports I've gotten so far would have benefited from it: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by ProfessorMeowingtons** [comment]
Well, you learn something new every day.
Anyway, I installed the latest version of BP and removed all the other mods except for BP and The Midnight mod. Upon entering the Midnight dimension the bubble/blob phase effect still happens but no crashes, save for a huge amount of lag that happened once. However, upon installing back Quark and Autoreglib and entering the Midnight dimension, it once again crashes a few seconds later.
[crash-2019-07-20_18.08.28-client.txt](https://github.com/Johni0702/BetterPortals/files/3414038/crash-2019-07-20_18.08.28-client.txt)

**Comment by Johni0702** [comment]
This is an issue with Autoreglib, see my (updated) comment in: https://github.com/Vazkii/AutoRegLib/issues/33
