### ISSUE TITLE
VanillaFix breaks portal texture animation

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#170]
The Portal's texture refused to animate in my modpack, but does on it's own.
The mods in my pack:
![Screenshot (31)](https://user-images.githubusercontent.com/53196852/61727279-09c69700-ad41-11e9-839b-1918820e2ed4.png)
Also, please add a config opition to MUTE the other side of portals.

**Comment by Johni0702** [comment]
Could you please try to reduce the amount of third-party mods. My guess would be one of BetterFPS, VanillaFix and/or Foamfix.

**Comment by Johni0702** [comment]
Tracking the option to disable sounds in #171

**Comment by TheMCSpacePro** [comment]
All right, found the problem. Add "VanillaFix" to the list of incompatible mods.

**Comment by Johni0702** [comment]
The source code of VanillaFix is freely available, so fixing the issue should be a lot less of a hassle than e.g. OF would be. Therefore I'd rather fix the issue instead of just accepting its existance.

https://www.curseforge.com/minecraft/mc-mods/vanillafix
https://github.com/DimensionalDevelopment/VanillaFix

**Comment by TheMCSpacePro** [comment]
Oh, ok. I'll wait for the fix then.

**Comment by rvveber** [comment]
Can we get a fix for this? This problem is beeing experienced with other textures from other resourcepacks and mods and it would not just help BetterPortals!

**Comment by TheMCSpacePro** [comment]
This WAS fixed! Did you not see the line "Closed #170 via 1f79d7e"?
