### ISSUE TITLE
Portal rendering completely broken

### ISSUE THREAD

**Issue by InfiniDelta** [Johni0702/BetterPortals#192]
Well, i downloaded this mod and then this happened
http://prntscr.com/omavkk
Yeah i don;t know whats happening but i don;t think that;s how this mod's supposed to work.

**Comment by Johni0702** [comment]
Needs more information. BP Version? Other mods? Logs?
You might want to read [this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) article about how to make effective bug reports.

**Comment by InfiniDelta** [comment]
Oddly enough it fixed itself after i restarted the game so I can't recreate it for a more detailed report.
I think I know what caused it anyways, though. Sildurs Vibrant Shaders Lite (With optifine). Lighting a portal with these shaders on will just yield a completely black portal, and the bug happened right after i turned the shaders back off.

**Comment by Johni0702** [comment]
The black portal with shaders is intentional as OF does not (and does not plan to) support rendering of multiple worlds (see CF description), so I BP intentionally disables its see-through part when shaders are active.

OF does some stuff when turning shaders on/off and I'm guessing that doesn't work with multiple worlds either.
With OF being proprietary, there's not really anything I can do about it, so I'm going to close this as not-our-bug and just add a note to the section in the CF description.
