### ISSUE TITLE
Nether Portal in the End?

### ISSUE THREAD

**Issue by MCSuperplayer** [Johni0702/BetterPortals#194]
I am playing my own Skyblock Modpack and just killed the Ender Dragon
I wanted to leave the End but the Portal didnt work.
I thought: maybe I can build a Nether Portal (I didnt realy believe it would work) but it worked!
I now have a Nether Portal between Overworld and Nether and Next to it another Portal between Nether and The End!
![2019-07-31_22 27 02](https://user-images.githubusercontent.com/53540819/62246835-cb864300-b3e4-11e9-91f8-6a085d894beb.png)
![2019-07-31_22 27 12](https://user-images.githubusercontent.com/53540819/62246844-cf19ca00-b3e4-11e9-86ec-f8d29a66a4ad.png)
![2019-07-31_22 27 15](https://user-images.githubusercontent.com/53540819/62246847-d0e38d80-b3e4-11e9-8587-16906d70a9af.png)
![2019-07-31_22 27 27](https://user-images.githubusercontent.com/53540819/62246849-d214ba80-b3e4-11e9-86ea-2141d3df196d.png)
![2019-07-31_22 28 22](https://user-images.githubusercontent.com/53540819/62246855-d3de7e00-b3e4-11e9-99ce-231818455ae5.png)

**Comment by Johni0702** [comment]
I'm inclined to call this a feature rather than a bug.
The reason vanilla doesn't support this is (at least partly) by necessity since their portals do not have any state (i.e. they're neither entities nor tile entities), so they cannot store their destination dimension.
BP portals do have state since they need to remember their exact remote position, so they also remember their remote dimension.

Is there some gameplay-related reason that this should be forbidden?
And if so, how should portals in the end behave? IIRC vanilla portals act as one-way portals to the overworld which doesn't really work with BP portals.

**Comment by MCSuperplayer** [comment]
Thats good! Please dont change this!
