### ISSUE TITLE
Issue with chisels and bits mod

### ISSUE THREAD

**Issue by Panduso** [Johni0702/BetterPortals#202]
When i used the chisels and bits mod, i couldn't place or break normal blocks but it worked fine when i removed better portals.

**Comment by Johni0702** [comment]
Needs more info, log, etc.
As is, I can place both blocks and bits just fine.

**Comment by Panduso** [comment]
ok, when i use the chisels and bits mod, i place some bits and stuff, but after that i cant place or remove any normal blocks

**Comment by Johni0702** [comment]
Nope, placing bits and normal blocks in any order is working just fine for me.

**Comment by Panduso** [comment]
huh, ok i'll make a video

**Comment by Panduso** [comment]
and i am on 1.12.2 by the way

**Comment by Panduso** [comment]
[2019-08-05 13-46-52.zip](https://github.com/Johni0702/BetterPortals/files/3467419/2019-08-05.13-46-52.zip)
video is in here

**Comment by Johni0702** [comment]
That looks like an old BP version.
You have yet to provide any log where I could check, so I'm going to stop responding until you do.

**Comment by Panduso** [comment]
[latest.txt](https://github.com/Johni0702/BetterPortals/files/3467502/latest.txt)
here's the log

**Comment by Johni0702** [comment]
You have seven other mods installed. Remove them and try again. If it still happens, post an updated log. If it no longer happens, re-add them until you find the minimal combination of mods required to reproduce the issue.

Also, since you have not at all mentioned this but you're doing it in your video: Is the going through two different portals are required step to reproduce this? Does it happen if there aren't any portals? Does it happen if there are portals but you're not using them? Does it happen if there's one portal and you've went through it once? Please read the article I posted above.

**Comment by Panduso** [comment]
i only have 4 other mods, the others are core mods and i tried without world edit

**Comment by Panduso** [comment]
which are chisels and bits, extra bit manipulation, flat colored blocks and little tiles i'll try without them

**Comment by Panduso** [comment]
oh, i figured it out! it was the flat colored blocks mod that made the issue

**Comment by Panduso** [comment]
the issue happened again and i have removed the mods

**Comment by Panduso** [comment]
its world edit that does it
