### ISSUE TITLE
Journey Map ATM3 Server

### ISSUE THREAD

**Issue by Pathos14489** [Johni0702/BetterPortals#249]
I recently tried adding this into AllTheMods 3 (MC 1.12.2, ATM 5.12.1) and found that at least in the server space, JourneyMap caused the server to crash, and when it didn't crash, the portals refused to open. After removing it from the server, it worked fine. (I use VoxelMap client-side, so I am unsure if it's incompatible client-side as well) Also I'm sorry but I can't figure out the label thing.

**Comment by Johni0702** [comment]
Since you didn't specify your JourneyMap version, I'm assuming this is the same as: #38
If it's not, then please provide more information (the crash report for a start).

If you're referring to GitHub labels, then don't worry about them. I don't think you can assign those unless you're a moderator for the repo.
