### ISSUE TITLE
Twilight Forest Portals don't work inside small areas

### ISSUE THREAD

**Issue by Dalethium** [Johni0702/BetterPortals#261]
Twilight forest portals in overworld structures are unusable as they get stuck in the ceiling of the overworld structure making you unable to exit

https://pastebin.com/xGKg4eRu my mod list

PS: I love this mod, it's great! Keep up the good work.

**Comment by Johni0702** [comment]
In general, please open multiple issues if you have multiple issues because that allows them to be handled individually.
3 happens to be working as intended. It just happens that the intended way can be confusing if you don't know the intention. I've created #262 to address that.
2 is this issue now.

I'm not sure how to fix it though.
Having the vanilla TF portals link directly to each other (instead of having separate exit portals) seems like it wouldn't be an option for a ton of reasons, primarily the fact that inverting gravity will lead to tons of logic and rendering problems (and would require changes to a ton of things in BP) but also the fact that TF generates one of them, so they can have a different shapes.
Searching for unobstructed space when linking solves only half the issue since people can still (even inadvertently) put blocks there after the portals are linked. Makes me wonder what TF does if you fill in all blocks around the portal.
Maybe the best idea is to get rid of the vanilla TF portals and just treat them like lying nether portals (i.e. generate the remote portal in the air, directly link them and then allow them to be used from either side). The only real downside to this option would be its lack of compatibility, i.e. neither compatible with old BP versions nor with already existing TF portals (because their shapes can be different and both are on the ground).

**Comment by Dalethium** [comment]
Perhaps you could have better portal frames simply remove a 2x2 area around the portal breaking the blocks (other than things like bedrock to prevent bugs), this way for normal survival usage, someone could make the portal and then be able to exit it - dealing with the other side themselves? 

or maybe you could make it so the portal simply won't open, stating that the other side is obstructed?
