### ISSUE TITLE
World unloading issues

### ISSUE THREAD

**Issue by Dalethium** [Johni0702/BetterPortals#263]
[Relevant bits](https://pastebin.com/WAGjui1y)
[Full Log](https://pastebin.com/raw/DNE7BZLq)
[Mods](https://pastebin.com/4XTridXS)
The client did not crash, however on quitting/unloading a multiplayer world, a large array of errors popped up. Much of the stack trace involved this mod.

Seeing as this isn't a crash and more just unhandled exceptions I don't think it's a big issue, but it should be documented none the less.

**Comment by Johni0702** [comment]
That's unfortunately a vanilla issue which has been fixed in 1.13 (or 1.14, don't remember).
Minecraft doesn't clear the queue of yet-to-be handled packets on disconnect, so those packets are still handled even though the world is already unloaded. Having packets for multiple worlds just makes it more noticeable.
I could clear the list manually but some mods actually rely on that behavior (because they use it as a general task queue), so I'd rather not do that.
