### ISSUE TITLE
White Screen and OpenGL error 1282

### ISSUE THREAD

**Issue by toxiclim3** [Johni0702/BetterPortals#273]
When I load in my world all i can see is white and my HUD. Also i can see a message in chat saying "OpenGL Error:1282 (Invalid Operation)"
![2019-08-23_09 55 50](https://user-images.githubusercontent.com/54431997/63572823-7c1ed700-c58c-11e9-862f-4023bd5517fb.png)

**Comment by toxiclim3** [comment]
Update:I managed to get out of my house and walk up to my portal and my screen started flickering white instead of pure white. I broke my(Nether) portal and my game crashed. 
Link from VanillaFix: paste.dimdev.org/ticacemuka.mccrash

**Comment by Johni0702** [comment]
The crash shows someone using an unlinked nether portal (#265), it doesn't appear to be related to destroying the portal, though it might be if someone/thing was using the portal at the same time (either way #265 is fixed in the next version).

Now for debugging the white screen (it's a known issue but I'm unable to reproduce it and have yet to receive detailed info on what causes it):
1. Backup your whole .minecraft folder
2. Remove all mods except BP, Forgelin and Optifine
3. Issue should still exist (at least it did for others)
4. Remove the optionsof.txt file in your .minecraft folder to reset OF settings
5. Issue should disappear (at least it did for others)
6. Restore the optionsof.txt file from your backup
7. Issue should re-appear (but it didn't for others)
8. Restore the whole .minecraft folder from your backup (other people didn't have a backup)
9. ???

**Comment by toxiclim3** [comment]
Removing mods Fixed the issue,i will try and test which mod made my game not work

**Comment by toxiclim3** [comment]
I Tried to add mods in chunks of 10 to betterportals and nothing crashed,so i guess removing mods and readding them somehow fixed the it?
Also i was in singleplayer and i found this too?
![CompressedWeirdPortal](https://user-images.githubusercontent.com/54431997/63584365-797cab80-c5a5-11e9-9588-31389fb4d88f.gif)

**Comment by Johni0702** [comment]
Might be that some of the configs changed. I hope you did step 1 so you can jump right to step 8.

The other thing is a separate thing, please open a separate issue for it and explain more of what's going on (e.g. how portals are linked, how the second portal is relevant, how to reproduce it, etc.).

**Comment by toxiclim3** [comment]
I did do step 8,that's already the version with all the mods back. So i Guess case closed?
