### ISSUE TITLE
Crash on disconnect

### ISSUE THREAD

**Issue by Dalethium** [Johni0702/BetterPortals#279]
Not sure if it helps, but I disconnected because my internet went out.
https://paste.dimdev.org/qesapazome.mccrash
--EDIT--
Related crash on a friends game when the server stoppped
https://paste.dimdev.org/bomohugixo.mccrash

**Comment by Johni0702** [comment]
First one should be fixed as of BP 0.3.7.5 by https://github.com/Johni0702/BetterPortals/commit/a7a59958fce52f657af8e7d7cf2a9e89c7f540f2.
Second one has likely been fixed by now as well. If it's still happening with a more recent version of BP, please post the new crash report (and the game log) for it.
