### ISSUE TITLE
Better Portals Ideas

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#311]
Some ideas I had while walking around and talking to myself. I added all 4 to one list to avoid cludder. Here they are!

1- Mob Seeking Through Portals

Pretty easy. Makes it so that you can't use portals to escape mobs. Either hositle or pets, you can't use the better portals to get away. To put it simple - mob following you sees you enter portal, mob follows you through portal. Pets know you've entered portal even if they dont see you. They can also see you on the other side (unless "See-Through Portals" is turned off) meaning they can still give chase. I'll understand if THIS doesn't make it for a LONNG time.

2- Better outside travel

Instead of just poping to the other side, the entity could be seen slowly appearing on the other side as more of them goes through. Best seen when portal opacity is 0 as the portal is invisible. It looks as if they are just moving through air.

3- Submods

A submod is a mod that while heavyly intergrating with the base mod, doesn't require it, different from a addon, which refuses to allow the game to load if the base mod isn't located. (The term "submod" was created by me, first used here.) The first one for Better Portals would just be porting the Bedrock End Portal shaders to the Java End Portals. (Yes, they are different.) Here is a quick link to them: https://www.mediafire.com/file/20opnph2sn26gbo/Bedrock_End_Portal_Shaders.zip/file

4- Even Better End Portals

The portals would no longer be stuck at 3x3 and would no longer reqire the frame.

Really hope you can add these! Though I undertand if you cant/dont want to.

**Comment by Johni0702** [comment]
1. See #63, I've since had a closer look at it and, yeah, turns out to be incredibly hard to do
2. Not entirely sure what you mean. If you're referring to the exit-end of one-way portals (e.g. end portals or twilightforest portals), those have already been changed (mostly for proper collision detection) in BP 0.3, I'd suggest you take a look at it.
3. I'd be somewhat surprised if such a mod doesn't already exist. And, if it merely hooks the end portal tile entity renderer, then it should work out of the box with BP (except it'll probably not respect BP's opacity setting).
4. The 3x3 shape isn't a hard requirement for the portal itself (you could even go in and edit the portal entity's NBT to change it) and neither is the frame. But how would that work from a gameplay perspective?! Frames are essential there (how would frame-less portals know their initial shape?) and you cannot even pick them up in survival (so you'd be stuck at 3x3 in survival anyway).
I'd also like to keep fundamental, (potentially controversial) gameplay changes to minimum if at all possible.

**Comment by TheMCSpacePro** [comment]
All right. I'll go refine the ideas, keep 3 (the idea of submods). And for 2, I was referring to portals like the Nether Portal, though if you already have the code for it in the end and twilightforest portals, then it (hopfully) should be a simple CTRL-C, CTRL-V (copy patse) to get it working. Also I cant find a mod that ports the shaders, so I'm asking you to make one. I'd be happy to playtest it.

**Comment by TheMCSpacePro** [comment]
And 4 was meant for map makers and creative mode players.

**Comment by TheMCSpacePro** [comment]
And the only other one I was talking to myself about:

Force Load Config

This config option (false by default) would load the currently available better dimentions (so it wouldn't load the dimentions you dont have the mod for, IE wouldn't load the aether if you didn't have the aether mod) when either A. The world is loading, or B. the moment the dimention unloads. This would mean that the when you activate the portals, they would be made the next frame like a old portal (a portal that isn't a better portal) would be. Of course the FPS might not like it, but hey, if your trying to do a epic reveal to your friends, then you dont have to worry about the portal appearing as if it doesn't work for a few seconds before freezing before the portal appears. To put it simply, the dimention would force load itself if the dimention isn't already loaded to speed up the time between the portal being activated and when you can go through it.

**Comment by Johni0702** [comment]
2. I don't get what you mean then. There shouldn't be any `poping` of entities and having them slowly appear makes no sense because they're always visible. Please explain exactly what you are seeing where and how you would want to to be changed.
3. I'm not really interested in writing that mod. If you can find someone to do it and they need help getting it to work with BP, then I'll be happy to help.
4. There is #231 which sounds like what you mean.
5. There are actually four different things which one could referring to as "loading":
   - Terrain Generation: 95% of the time between the portal being ignited and it opening is used by Minecraft to generate the terrain, there's no way around that since you really can't pre-generate an infinite world. Since vanilla doesn't link portals, it only starts generating once you enter the loading screen (very noticeable for anyone else on the server).
   - Loading already existing chunks from disk, usually goes fairly quick, especially compared to terrain generation. Pre-loading the whole generated world would require unreasonable amounts of RAM.
   - Sending chunks from server to client (yes, even singleplayer has an internal server), for SP a fraction of a second, for MP a few seconds. Nothing one can really do about this one, the world somehow needs to get from the server to the client and that takes time.
   - Converting the blocks into renderable geometry and uploading those to your GPU. This is what you actually see and is usually slower than all of the above. It's also incrementally though (i.e. happens over multiple frames), so it shouldn't matter.

**Comment by TheMCSpacePro** [comment]
2. Cant really explain it. The poping is only seen in 3rd person mode when the camera is looking through the portal.
3. All right. I'll see if I could make it (when I get the time). I'll just need a quick how to on how to replace the shaders and I should be on the roll.
4. Yea, that is exactly what I mean.
5. Didn't know that before you told me.

**Comment by TheMCSpacePro** [comment]
Alright, no more ideas. Going ahead and closing this.
