### ISSUE TITLE
Portal does not cull occluded block faces

### ISSUE THREAD

**Issue by InsomniaKitten** [Johni0702/BetterPortals#32]
**Better Portals version:** [0.1.3](https://minecraft.curseforge.com/projects/betterportals/files/2717887)
**Better Foliage version:** [MC1.12-2.2.0](https://minecraft.curseforge.com/projects/better-foliage/files/2631951)

The area where the portal is rendered does not cull adjacent faces that are occluded whilst the portal view is rendered. This causes issues with mod's such as Better Foliage, as seen below, where it draws additional quads for the un-culled face.

![Screenshot of BetterFoliage conflict](https://i.imgur.com/oH6Uj1i.png)

**Comment by Johni0702** [comment]
This is a bit tricky because you actually want to see the grass when looking from the other side (below in overworld or above in nether) but I guess no floating grass in portals is better than too much floating grass in portals.

For future reference: [this](https://github.com/octarine-noise/BetterFoliage/blob/73223c15c3ac537e059e019d2de9df01be298fd0/src/main/kotlin/mods/betterfoliage/client/render/RenderGrass.kt#L105) is the check portal blocks currently fail.

**Comment by Johni0702** [comment]
Actually, this is more troublesome to resolve than I though it would be and will probably also require changes on BetterFoliage's part. At the very least https://github.com/octarine-noise/BetterFoliage/issues/173 should be fixed, which, depending on how it's implemented, might even be enough, so I'm closing this issue in favor of that one.
