### ISSUE TITLE
Howling Moon Mod and Better Portals

### ISSUE THREAD

**Issue by Veoxyz** [Johni0702/BetterPortals#347]
Hi, i cant see myself when I becoming a Werewolf after I installed the Better Portals Mod.
So what can I do?

-Veoxyz

**Comment by Johni0702** [comment]
The Howling Moon mod does not provide any source code, so I'm unable to look into this.
I suggest you bring it up to its developer(s). As is, it's up to them to fix this.
Chances are they're doing something similar to Ido (see #200) and even if they don't, my response over there should be helpful to them anyway.

**Comment by Hydraheads** [comment]
This issue also happens with cyberware's 1.12 port upon getting mechanical parts that render...

**Comment by Johni0702** [comment]
"Robotic Parts" (cyberware's unofficial 1.12 port) has the same issue as Ido (#200) in that they're copying verbatim large parts of the player render (though for better reasons than Ido) thereby bypassing any modifications which BP has made to it.
One of those modifications is to allow the user's player entity to be rendered when looking through a portal (or in third-person, technically the same thing as far as BP is concerned).

Related Robotic Parts issue: https://github.com/An-Sar/Cyberware/issues/16

Ideally this is fixed in Robotic Parts / Ido / possibly Howling Moon but because it appears to be a common type of misbehavior and all of those tickets have been open for quite a while already, I'll see if I can find an alternative approach to fixing player rendering which works even when the vanilla code is completely duplicated (i.e. unpatchable).
