### ISSUE TITLE
Crash at startup in DDSS pack

### ISSUE THREAD

**Issue by drago87** [Johni0702/BetterPortals#370]
Addedbetter portals 0.3.5 to [DDSS](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles) v5.7b and the game crashes before the minecraft window open.
Need to manualy terminate java via task manager to restart minecraft.
No crash report but here is the log file
[latest.log](https://github.com/Johni0702/BetterPortals/files/3647972/latest.-.Copy.log)

**Comment by Johni0702** [comment]
This is an issue in p455w0rdlib's coremod, see https://github.com/p455w0rd/p455w0rds-Library/issues/26 or https://github.com/p455w0rd/p455w0rds-Library/issues/27 which appear to be closed even though they don't appear to be resolved or https://github.com/p455w0rd/p455w0rds-Library/issues/51 which is still open.

Side note: I saw you've got creativecore+littletiles installed, make sure it's the version from https://github.com/CreativeMD/LittleTiles/issues/237 or a more recent one, otherwise you'll run into issues later on.
