### ISSUE TITLE
Game does not launch if adding this mod to Dungeons, Dragons, and Space Shuttles v6.2 modpack

### ISSUE THREAD

**Issue by EndangeredProdigy** [Johni0702/BetterPortals#385]
Once play is clicked from the Minecraft Launcher, the game does not open the Minecraft window.  It sits at using 812mb in the task manager.  No crash log available because the game does not actually crash, just never opens.

**Comment by Johni0702** [comment]
Please attach the game log. It should be available in the `logs` folder and in the launcher.

**Comment by Milii20** [comment]
[latest.log](https://github.com/Johni0702/BetterPortals/files/3773506/latest.log)
Greetings!, i am having a similar problem in another modpack but i cant find which mod is conflicting with betterPortals (as soon as better portals is removed, game launchs without problems), the game doesnt launch the minecraft window, no crashlog, only this latest.log and that's it, aparently it's stuck because "mixins.betterportals.json:MixinEntity target net.minecraft.entity.Entity was already transformed"

**Comment by Milii20** [comment]
found it, vanillafix transforms net.minecraft.entity.Entity, disabling either vanillafix or betterportals allows the game to launch, DD&SS also has vanillafix

**Comment by Milii20** [comment]
also aparently LagGoggles tries to do the same transform and fails because betterPortals already used it, causing the following:
[18:18:33] [Client thread/FATAL]: Not all required mixins have been applied!
[18:18:33] [Client thread/FATAL]: To prevent you from wasting your time, the process has ended.
[18:18:33] [Client thread/FATAL]: 
[18:18:33] [Client thread/FATAL]: Required mixins that have not been applied:
[18:18:33] [Client thread/FATAL]: - cf.terminator.laggoggles.mixin.MixinEntity targeting: net.minecraft.entity.Entity
[18:18:33] [Client thread/FATAL]: 
[18:18:33] [Client thread/FATAL]: This means that LagGoggles will not function properly.
after this, the game totally crashes before launching the minecraft window

**Comment by Johni0702** [comment]
@Milii20 This is actually neither BetterPortals' nor VanillaFix's fault.
It's p455w0rdslib's coremod which is broken and will cause other mods (more than just BP and VF) to fail seemingly at random (in reality it depends on the order in which mods load other parts of the game which is why you didn't see the error when removing either of the two mods).
See the issues linked in https://github.com/Johni0702/BetterPortals/issues/376 for more information.

I don't see any easy way on CurseForge to check if p455w0rdslib is included in DD&SS but I'm going to close this issue under that assumption (and because OP hasn't yet replied anyway).
