### ISSUE TITLE
Crashing with Vivecraft non-VR companion

### ISSUE THREAD

**Issue by Techjar** [Johni0702/BetterPortals#404]
```
Mixin apply failed mixins.betterportals.json:MixinEntityRenderer -> net.minecraft.client.renderer.EntityRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Redirect ctor invocation was not found in net/minecraft/client/renderer/EntityRenderer::func_175068_a(IFJ)V
```

This seems weird considering our non-VR client doesn't touch EntityRenderer. Maybe mixins meant for the VR client are mistakenly being applied here? Not sure how you're doing the Vivecraft detection.

**Comment by Johni0702** [comment]
I'm enabling/disabling vivecraft mixins based on the existance of one of VC's coremod classes: https://github.com/Johni0702/BetterPortals/blob/08c793dc2117becc8e95855b55c9f566b936a769/src/api/java/de/johni0702/minecraft/betterportals/impl/BetterPortalsMixinConfigPlugin.java#L20
However all mixins which are dynamically enabled/disabled have names ending in `_OF`, `_NoOF`, `_VC`, `_NoVC`, etc., so that's probably not it.
Could you quickly link me to the source for the companion mod? I'll be able to take a look at it in about an hour or so.

**Comment by Techjar** [comment]
`org.vivecraft.asm.VivecraftASMTransformer` also exists in the non-VR client, so you may want to pick something a bit more concrete like `org.vivecraft.provider.MCOpenVR` if you need to detect the VR client specifically. Though since you mention the suffix thing, that may not be the issue in this case, but still worth considering what effect it might have.

I'll get the patches for non-VR as soon as I can. I don't have them on hand so I'll need to either generate them or get them from jrbudda. In hindsight we should be pushing that to a branch on the GitHub repo.

**Comment by Techjar** [comment]
Oh, my bad on not checking the version. At least the issue is still valid with a different error.

The non-VR client is built on a separate branch with only the pieces of code needed for VR animations. We use the same build system and just run the different source through it. Here's the patch files if still needed: https://cdn.discordapp.com/attachments/195502278508150784/639531417201672212/patches_1.12_nonvr_9r1.zip

**Comment by Techjar** [comment]
Any progress on this?

**Comment by Johni0702** [comment]
No. I don't imagine it being particularly difficult, I just haven't gotten to it yet.
