### ISSUE TITLE
Interoperability issue with p455w0rdslib

### ISSUE THREAD

**Issue by dequbed** [Johni0702/BetterPortals#410]
When using Better Portals and p455w0rdslib you get graphical issues:

![2019-11-14_16 32 12](https://user-images.githubusercontent.com/3063480/68871738-3130dd80-06fd-11ea-91c4-3893142792ce.png)
![2019-11-14_16 30 39](https://user-images.githubusercontent.com/3063480/68871748-33933780-06fd-11ea-99f2-10718f74b274.png)

Screenshots were taken on Minecraft version 1.12.2 with
- Forge 1.12.2-14.23.5.2838
- p455w0rdslib-1.12.2-2.2.156.jar (md5sum 56a57b60eff38f98cf0228b802df2322)
- betterportals-0.3.7.1.jar (md5sum d11bf3d057509a11b8738df604094d46)

## Workaround
This issue can be worked around by setting `EnableShaders` to `false` in p455w0rdsLib.cfg.

I've opened a related issue in p455w0rds-Library's repository: p455w0rd/p455w0rds-Library#54

**Comment by Johni0702** [comment]
p455w0rdslib must in its vertex shader set gl_ClipVertex to the correct value (it doesn't currently set it at all).
GLSL spec (see 7.1): https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.1.20.pdf
This might also help: https://bugs.freedesktop.org/show_bug.cgi?id=64668#c12

**Comment by p455w0rd** [comment]
thanks for the reply @Johni0702 ..my glsl knowledge is (i think obviously) limited. I wouldn't know how to calculate the clip values/what gl_ClipVertex should be set to. I've given a lot of thought to removing the shaders/coremod from pwlib and likely will since I don't have the time to continue learning about glsl.
