### ISSUE TITLE
Issue with Thaumcraft

### ISSUE THREAD

**Issue by Digy95** [Johni0702/BetterPortals#42]
Mobs from Thaumcraft which are in the nether will have their models corrupted.

**Comment by su1c1d3jerk** [comment]
To add to this, the overworld mob models also seem to corrupt once you come out of the nether.

The Embers Rekindled Ancient Golem fireball model also breaks.

**Comment by Johni0702** [comment]
Can confirm, seems to still be happening. I also tried running a snapshot of BP 0.2 and it seems to have been fixed by one of its changes (guessing https://github.com/Johni0702/BetterPortals/commit/46ad6a612b9e56a2881bdf55138a6192ce351d52), so I'm probably just going to leave this issue open until 0.2 is released.
