### ISSUE TITLE
Portals do not teleport entities in minecarts

### ISSUE THREAD

**Issue by technologicalMayhem** [Johni0702/BetterPortals#43]
Minecarts all by themselves are capable of travelling through the portal all fine. However when a player is sitting in the minecart and it is sent through the portal with the player, it just simply drives through the portal without getting teleported to the nether in the process.

**Comment by CursedFlames** [comment]
AFAIK this happens in vanilla as well. Would be nice to fix it in this mod though, given how many other portal quirks it fixes.

**Comment by technologicalMayhem** [comment]
I just tested this. In vanilla minecarts with any that have a entity riding them don't go through portals. My guess is that vanilla intentionally prevents this, since teleporting two entities and making sure they end up in the right way on the other side is probably more complicated than useful.

**Comment by Johni0702** [comment]
As of BP 0.2, this should now be mostly working.

The only configuration which still cannot use the portal are players which act as vehicles. I don't think it's even possible in vanilla for the player to be the vehicle. So, given that, I don't think it's worth implementing especially because doing so is insanely more complex than the other way around.
