### ISSUE TITLE
Crash on disconnect from server near portal.

### ISSUE THREAD

**Issue by minelolpride** [Johni0702/BetterPortals#432]
The game appears to suddenly crash when disconnecting from a server, but only when near any portal. Singleplayer is unaffected. Configs for the mods on both sides are all default values.

BetterPortals v0.3.7.4
Forgelin v1.8.4

Reproduction:
 - Have a server with BP + Forgelin installed
 - Join the server, having only BP + Forgelin in mods
 - Create a portal of any kind (nether, end, etc. if more mods)
 - After lighting the portal, disconnect from the server. Minecraft should crash at this point

Crash logs (tested on a couple different computers)
https://hastebin.com/vevicilero.sql
https://hastebin.com/itacilusoc.php

On another note, these crashes were generated in similar fashion but with more mods present. I do not know if these would be worth looking at due to the presence of other mods. I noticed the errors were different so if it helps, here they are.
https://hastebin.com/abosidakox.rb
https://hastebin.com/lunonaceqa.rb

Thank you.

**Comment by Johni0702** [comment]
Thanks for the report.
I haven't yet tried it myself but given I rarely test on servers (cause it's basically twice the effort with 99% identical behavior), the issue seems fairly plausible. The difference probably comes from the fact that when you press Save And Quit in SP, it closes the integrated server (and unloads all worlds) **before** you actually disconnect from it, so at the time of disconnection, you never have any secondary worlds loaded. On a server however, you may disconnect while still having secondary worlds loaded and I seem to unload them too late. Should be fairly easy to fix.

The latter two exceptions are actually expected to happen, even in vanilla MC (they were fixed only with 1.13). However, normally they only print their info to the log and don't cause a full crash report. I assume VanillaFix changes that and while it ignores those errors happening in vanilla, it seems to not ignore them when they're triggered from BP.
I'll have to take a look at VanillaFix' sources at some point to figure out why that's happening, so I've split that off into its own issue: #433

**Comment by DarethZ33** [comment]
I have noticed this happening in multiplayer still on version 0.3.7.4, is this still occurring?

**Comment by DarethZ33** [comment]
Is there an update on when the fix is expected to be released?

**Comment by Johni0702** [comment]
Should be fixed as of BP 0.3.7.5.
If it's still happening after updating, please post the new crash report (and the game log) for it.
