### ISSUE TITLE
Remotely loading a different dimension

### ISSUE THREAD

**Issue by Hyxaru** [Johni0702/BetterPortals#443]
In vanilla minecraft, it is possible to load chunks in another dimension for a small amount of time, when an entity passes through the portal. This can be done (in the spawn chunks or otherwise loaded chunks) even if the player is far away. 
Better Portals has the convenience that it always loads the other side of a portal, not requiring to repeatedly force an entity through in order to load.

I've noticed however, that Better Portals-portals only load the connected chunks if the player is near the portal/loading the portal himself. Having a portal in the spawn chunks will not keep the other side loaded if the player is not near.

I assume this is likely an intended mechanic to prevent loading too many chunks, only starting rendering and loading the chunks on the other side once a player is in proximity. 
Question is, is there a way to willingly load multiple dimensions without being in proximity of the portal?

**Comment by Johni0702** [comment]
Technically (*simplified*), BP portals don't load the remote side at all. They merely spawn a fake player in the remote dimension for any nearby players in the local world. And it is that fake player which loads the remote portal (and nearby chunks).
So, without any players nearby, the remote portal will normally not be loaded and the portal will not be functional.

For a time, BP portals did load the remote chunks whenever needed but that lead to constant reloading of the remote world whenever any entity was near the portal (because the portal has to simulate collision boxes of blocks on the other side, mainly for vertical portals, so it needed to load the remote whenever anything was nearby).

There isn't any way to use BP portals to keep chunks permanently loaded and I'd argue there shouldn't be either. If you want a chunk loader, use a mod which provides a chunk loader.
BP portals should be working as expected if both sides are loaded via some third-party chunk loader.

**Comment by Hyxaru** [comment]
Ah I suspected such. For my own gameplay, I use Cubic Chunks and currently there is one chunk (cube) loader available, however that one does not load in it's dimension or stay alive when there is no player in it's dimension.

Still thanks for the heads up.
