### ISSUE TITLE
issue interacting with compact machines (CTD)

### ISSUE THREAD

**Issue by festro** [Johni0702/BetterPortals#475]
Interacting with compact machines either exiting or entering causes severe FPS drop during the bleedthrough transition and 2-3 times afterward will cause the server to shut down and boot me from the game with this crash report
[crash-2020-02-18_14.21.06-client.txt](https://github.com/Johni0702/BetterPortals/files/4221981/crash-2020-02-18_14.21.06-client.txt)

**Comment by Johni0702** [comment]
While the bleedthrough transition (usually called "enhanced third-party transfer") is certainly not inexpensive from a performance point (you are after all rendering two worlds at the same time). It may be significantly worsened by some other mod which does expensive stuff on world change which would usually be hidden by the loading screen.
If you don't know and don't care to know what's at fault, you can either remove the animation by setting 
"Enhanced third-party transfer duration" to 0, or completely remove the enhanced transfers (and get back the loading screen) by setting "Enhance third-party transfers" to false.

The crash appears to be caused by `extendedrenderer` (from CoroUtil). Similar compatibility issues have already been reported to CoroUtil (https://github.com/Corosauce/CoroUtil/issues/39) a while back, so I'd suggest removing it until those are resolved.

**Comment by festro** [comment]
ok, thanks for the heads up.
