### ISSUE TITLE
Better Portals and Chunk Loading

### ISSUE THREAD

**Issue by systemshaper** [Johni0702/BetterPortals#483]
I'm excited for this mod coming to 1.14.4! Based on the way this mod is implemented, do you expect it will be compatible with chunk loading features from other mods? The similar immersive portals mod seems to change chunk loading fundamentally such that all other chunk loading mods break, which is a deal killer for my server focused on auotmated farms! Hoping your mod will be an alternative that plays nicer with chunk loading.

**Comment by Johni0702** [comment]
My main focus with BP is on compatibility, so even though it also messes with chunk loading (there's really no way around that if you want your portals to work across large distances / dimensions), I'd generally not expect chunk loader mods to break because BP's changes.
Ofc it depends on how exactly the chunk loader mod is implemented but at least those which just use the vanilla `/forceload` (e.g. ChunkNoGoByeBye) should be working fine (I just tested `/forceload` with my local BP 1.14 fabric development version).

**Comment by systemshaper** [comment]
That's great news! It will give the players on my server hope that they can have their cool portals again someday. Thank you for your work, would love to add this to our server when you're ready for folks to start testing 1.14.4.
