### ISSUE TITLE
Crashes with latest Mixins update (Vanilla Fix etc,)

### ISSUE THREAD

**Issue by AechtRob** [Johni0702/BetterPortals#499]
The mod crashes at startup in conflict with the latest Vanilla Fix, which has some Mixins updates in it. (MC 1.12.2)

**Comment by Johni0702** [comment]
If this is what I think it is (can't tell without seeing the actual crash log), then there's no way to fix this other than updating Mixin in BP as well. Until then, you should be able to work around the issue by simply renaming the VanillaFix jar so it's loaded before the BP one (e.g. prepending `a` to its name).

**Comment by AechtRob** [comment]
Sadly Twitch/Curse won't support that method. It will reject the upload of a modpack containing a renamed file with a ! before its name if that file is added manually to the modpack zip. If you do not add it manually then Twitch parses the file as the straight VanillaFix mod with no ! anyway. Either way, until there is a fix there is no solution for public modpacks apart from uninstalling VanillaFix as well.

**Comment by dark-penguin** [comment]
I can confirm this, and also that the fix works (renaming VanillaFix to _VanillaFix so that it loads first).

I've had other similar problems with VanillaFix and something about mixins, and this solution would probably fix them too. (I don't know what "mixins" are, but if it's a matter of loading order, then loading VanillaFix before ANY other mods would fix all those things.)

Therefore, especially for Twitch launcher users, maybe it would make sense to ask VanillaFix to rename their default filename so that it always loads first? Due to the nature of VanillaFix, that would seem beneficial in all cases, especially since they seem to be on top of updating for the latest mixins.

Back to the issue at hand, if updating BetterPortals for newer mixins is not expected to happen any time soon, wouldn't it be possible to specify order loading for BetterPortals to "always load VanillaFix first if it is present"? This might make life easier at least for some users.

**Comment by dark-penguin** [comment]
Here, I've submitted a proposal to VanillaFix. Their issue tracker is also drowning in reports about this issue with many other mods.
https://github.com/DimensionalDevelopment/VanillaFix/issues/265

**Comment by AlienXtream** [comment]
dear god this was a tough crash to nail down... O.o

**Comment by Dvoric** [comment]
Renaming VanillaFix to _VanillaFix fixes the crash for me too ... however ... BetterPortals gives me constant spikes. It doubles garbage collection and cuts my FPS in half. =(

MC: 1.12.2
Forge: 2847
Optifine: F5
BP:  0.3.7.7
Forgelin: 1.8.4
Quark: 179 / AutoReg: 32
VanillaFix: 1.0.10-150
JEI: 291
No Resource Packs or Shaders
