### ISSUE TITLE
Visual bug with astral sorcery

### ISSUE THREAD

**Issue by alpharou** [Johni0702/BetterPortals#509]
Here's a GIF:

![tHkQr6PIxc](https://user-images.githubusercontent.com/8113318/79635134-6ab7ba00-816f-11ea-919b-fa38f6748cae.gif)

Forge 14.23.5.2847
astralsorcery-1.12.2-1.10.23
Forgelin-1.8.4
betterportals-0.3.7.7

**Comment by Johni0702** [comment]
That likely needs to be fixed in astral sorcery. Their sky rendering code probably assumes there to be only one world loaded on the client at any one time, which is generally true except when BP is installed.

**Comment by alpharou** [comment]
> That likely needs to be fixed in astral sorcery. Their sky rendering code probably assumes there to be only one world loaded on the client at any one time, which is generally true except when BP is installed.

Could you... file some kind of issue to them? I'd do that myself, but I'm not knowledgable enough to explain this issue.

**Comment by alpharou** [comment]
Well that was easy

**Comment by HellFirePvP** [comment]
> Their sky rendering code probably assumes there to be only one world loaded on the client at any one time, which is generally true except when BP is installed.

Well, rendering a 2nd world will cause the gateway shield - the black sphere shown flickering there - to stop rendering as it's not the world its associated source is in. Next tick the shield-effect gets spawned again since the tileentity is missing its shield-effect. Rince and repeat.

Not fixing this as development focuses on newer versions now.
