### ISSUE TITLE
aromas mining dim

### ISSUE THREAD

**Issue by ZEROX7** [Johni0702/BetterPortals#514]
hey 
iam just asking for a compatibility for aromas mining dimension mod

**Comment by Johni0702** [comment]
If by "compatibility" you mean adding a see-through version of MiningDim's portals, then no:
For non-trivial integrations, I'll generally only consider spending time with mods which are released under a GPLv3-compatible license (e.g. one of [these](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)). MiningDim isn't. There isn't even publicly available source code for it.

If you mean that there's some kind of crash or something, then provide details of that crash or whatever the problem is.
