### ISSUE TITLE
CME when making an end portal

### ISSUE THREAD

**Issue by Vazkii** [Johni0702/BetterPortals#70]
https://paste.dimdev.org/lowiziyopi.mccrash

**Comment by Redd56** [comment]
Is that vaskii... Holy fuckles

**Comment by Johni0702** [comment]
This looks to be asynchronous access or a core mod since the loop indicated by the stacktrace is fairly simple and doesn't do any modification by itself nor does it call any external code which allows for modifications to happen.
Based on cross referencing with #46, it's probably one of these mods which is doing the concurrent modification:
<details>

```
autoreglib               
blockcraftery            
charm                    
comforts                 
coralreef                
crafttweaker             
crafttweakerjei          
ctgui                    
earthworks               
extraalchemy             
foamfix                  
foamfixcore              
jaff                     
jei                      
mousetweaks              
multimob                 
mysticallib              
plated                   
primitivemobs            
quark                    
stg                      
```
</details>

I'll be installing them all to try to see if I can find any async access to that list.
