### ISSUE TITLE
Fake players are able to get advancements

### ISSUE THREAD

**Issue by Vazkii** [Johni0702/BetterPortals#71]
![2019-06-07_20 23 52](https://user-images.githubusercontent.com/1794735/59128591-6244ff00-8962-11e9-8001-b1c7eb6fb82e.png)

**Comment by Johni0702** [comment]
Above commit should suppress any advancements and statistics for view players.
However, since I'm unable to reproduce the original issue, (it's probably one of your many mods that's granting those advancements and it wasn't one of the ones I tried), I'm unable to confirm it as fixed.

Should this still occur on any future version (0.1.5+ or 0.2+), please re-open the issue.
