### ISSUE TITLE
Incompatibility with another mod

### ISSUE THREAD

**Issue by Zoofule** [Johni0702/BetterPortals#79]
There is a compatibility issue with the mod Xaero's Minimap where when you activate a nether portal while in the overworld, the map thinks you are in the nether and stops working in the overworld nearly completely. I posted an issue on there issue tracker and they recommended I post one here as well. Here is a link to there curseforge page [Xaero's Minimap](https://minecraft.curseforge.com/projects/xaeros-minimap)

**Comment by Johni0702** [comment]
Xaero's Minimap is closed source. As such I am unable to provide any significant support for it.

BP doesn't manually fire the world unload event, so it should only fire when the world is actually unloaded.
The `Minecraft.world` value has to change for Minecraft to be able to update and render the world. BP switches it out as required and the correct world should always be present during the corresponding events.
Ofc there will be tick and render events for all worlds which are currently loaded and that's what usually throws off third-party mods which keep their state per-client-instance instead of per-world. The fix is usually just to attach the mod's data to the world (in which ever way that makes the most sense: Capabilities, WeakHashMap, Mixin, etc.).
A minimap mod should also consider that the same remote world may be loaded multiple times at vastly different locations (e.g. for two portals which link to distant remote portals).

**Comment by Zoofule** [comment]
Ok, I messaged Xaero and copied what you said, maybe the two of you could work together to figure out a fix for the issue. I am not sure if there is anything further I could do to help, but if there is anything, please let me know.
