### ISSUE TITLE
Random Things End Portal Display Issue

### ISSUE THREAD

**Issue by Sonicx32** [Johni0702/BetterPortals#82]
The End portal which can be created through the Random Things mod does not display properly with BetterPortals installed.

**Comment by Johni0702** [comment]
Is this with 0.1.6?
I've fixed a similar sounding bug with Charm's end portals (#68) in 0.1.5 (though at first with bugs which were then fixed in 0.1.6). If you are on 0.1.6, does it world on 0.1.4 (i.e. before the Charm portal fix)?

Also, if you're indeed on 0.1.6, could you please elaborate on `not display properly`?
