### ISSUE TITLE
Mixin issue causing crash

### ISSUE THREAD

**Issue by Dragnier** [Johni0702/BetterPortals#90]
After hitting play on the launcher, the game crashes before it even loads forge. At first, I thought this might be another mod and posted the issue there. They have redirected me here. https://github.com/AranaiRa/ArcaneArchives/issues/11

[latest.log](https://gist.github.com/Dragnier/18aab56eaf2f22971be0f6abd3d9d472)

**Comment by Johni0702** [comment]
duely is correct in their assessment.
This looks like some some third-party (core) mod isn't playing by the rules and is causing the Entity class to be loaded earlier than it should be.
BP requires modifying that class and therefore crashes early if that fails.

It's fairly difficult to determine the mod at fault from the log, so I'd suggest removing third-party mods until you find the one responsible (should be fairly quick since it crashes within seconds).
Once you've found the mod responsible, report the issue to them.

**Comment by Dragnier** [comment]
Seems to be p455w0rds-Library
