### ISSUE TITLE
GLASS Incompatibility

### ISSUE THREAD

**Issue by RealArcanePhysics** [Johni0702/BetterPortals#91]
This mod is incompatible with General Layman's Aesthetic Spying Screen(GLASS). The game doesn't crash, but It seems to get confused about the player's location. I encountered this bug when I made a chamber for GLASS, and set it up for a terminal near a nether portal. When I activated the chamber, my directional controls were messed up(W to go right, A goes backwords, etc.), and my view was broken. I couldn't find the lever I placed, so I tried to break the chamber. Weirdly, I broke free, but I was at the camera's location. My view was broken, and I could see myself by a copy of the chamber. I tried to move toward it, and I notice my perspective kept switching between the one by the actual chamber, and the other one. I then realized the rendering bug I had was actually showing my real perspective, so I used that to break the projector. 
![2019-06-21_02 55 52](https://user-images.githubusercontent.com/26045097/59908948-31d67980-93d4-11e9-85b6-46fb67fe2089.png)
![2019-06-21_02 58 11](https://user-images.githubusercontent.com/26045097/59908954-34d16a00-93d4-11e9-8a3c-7048a82e1a02.png)

**Comment by Johni0702** [comment]
GLASS seems to copy verbatim lots of vanilla code (e.g. [here](https://github.com/iChun/iChunUtil/blob/a3269be29f5b1cf8486a5349dabaf21d21ec5346/src/main/java/me/ichun/mods/ichunutil/common/module/worldportals/client/render/WorldPortalRenderer.java) or [here](https://github.com/iChun/iChunUtil/blob/master/src/main/java/me/ichun/mods/ichunutil/common/module/worldportals/client/render/world/RenderGlobalProxy.java)) without any indication of what has been changed, making it quite difficult to tell what's going on and effectively removing any hook which BP has placed into the respective vanilla code.
It may be possible to add support for BP (via its View API which will be in 0.2) to GLASS (effectivlly using BP's rendering pipeline to do the portal rendering) but given the lack of clear separation between GLASS code and vanilla code (and lack of time), that's nothing I'm interested in doing myself.
It would also require changing GLASS's code to do the rendering of portals/glass/whateverGLASScallsit in sequence (at least when BP is installed) instead of recursively, not sure feasibly that is.
